#!/bin/sh -x
#DEV=sda1
DEV=mmcblk0p1

MOUNTP=/mnt/${DEV}
DEVICE=/dev/${DEV}

PGDATA=${MOUNTP}/postgres
PASSWAS=LoraWan
PASSWNS=LoraWan
RDDIR=${MOUNTP}/redis


help() {
        cat <<EOF
Syntax: chirpstack-helper [command]

Available commands:
  convertext4   Convert SD-Card to ext4 filesystem
  initpsql      Set postgresql database directory to ${PGDATA}
  initredis     Set redis database directory to ${RDDATA}
  initdb_as     Setup application-server database
  initdb_ns     Setup network-server database
  initdb        Setup network- and application-server database
  startall      Start network-server and application-server, ...
  stopall       Stop  network-server and application-server, ...
  backupdb      Save    to   current directory postgres database content and redis dump
  restoredb     Restore from current directory postgres database content and redis dump
Variables
  MOUNTP        ${MOUNTP}
  DEVICE        ${DEVICE}
  PGDATA        ${PGDATA}
  RDDIR         ${RDDIR}
EOF
}

convertext4()
{
	umount ${MOUNTP}
	mkfs.ext4 ${DEVICE}
	block mount
}

initpsql()
{
	/etc/init.d/chirpstack-application-server stop
	/etc/init.d/chirpstack-network-server stop
	/etc/init.d/chirpstack-gateway-bridge stop
	/etc/init.d/postgresql stop
	mkdir -p ${PGDATA}
	chmod 777 ${PGDATA}
	# /data/postgresql/data
	uci set postgresql.config.PGDATA=${PGDATA}/data
	uci commit
	/etc/init.d/postgresql start
}

initdb_as()
{
	sed -i "s/:Password/:${PASSWAS}/g"  /etc/chirpstack-application-server/chirpstack-application-server.toml
psql -h 127.0.0.1 -U postgres <<EOF
create role chirpstack_as with login password '${PASSWAS}';
create database chirpstack_as with owner chirpstack_as;
\c chirpstack_as
create extension pg_trgm;
create extension hstore;
\q
EOF
}

initdb_ns()
{
	sed -i "s/:Password/:${PASSWNS}/g"  /etc/chirpstack-network-server/chirpstack-network-server.toml
psql -h 127.0.0.1 -U postgres <<EOF
create role chirpstack_ns with login password '${PASSWNS}';
create database chirpstack_ns with owner chirpstack_ns;
\q
EOF
}

initdb()
{
	initdb_as
	initdb_ns
}

initredis()
{
	mkdir -p ${RDDIR}
	uci set redis.config.DIR=${RDDIR}
	uci commit redis
	/etc/init.d/redis-server stop
	/etc/init.d/redis-server start
	#RDDIR=`uci -q get redis.config.DIR`
	echo set redis data directory to ${RDDIR}
}

backupdb()
{
	# dump postgres database
	pg_dump -h 127.0.0.1 -U postgres -d chirpstack_as >chirpstack_as.sql
	pg_dump -h 127.0.0.1 -U postgres -d chirpstack_ns >chirpstack_ns.sql
	# backup redis data
	/etc/init.d/redis-server stop
	cp ${RDDIR}/dump.rdb redis_dump.rdb
	/etc/init.d/redis-server start
}

restoredb()
{
	# restore redis database
	psql -h 127.0.0.1 -U postgres chirpstack_ns <chirpstack_ns.sql
	psql -h 127.0.0.1 -U postgres chirpstack_as <chirpstack_as.sql
	# restore redis data
	/etc/init.d/redis stop
	cp redis_dump.rdb ${RDDIR}/dump.rdb
	/etc/init.d/redis start
}


startall()
{
	/etc/init.d/redis-server start
	/etc/init.d/postgresql start
	/etc/init.d/chirpstack-application-server start
	/etc/init.d/chirpstack-network-server start
	/etc/init.d/chirpstack-gateway-bridge stop
}

stopall()
{
	/etc/init.d/chirpstack-application-server stop
	/etc/init.d/chirpstack-network-server stop
	/etc/init.d/chirpstack-gateway-bridge stop
	/etc/init.d/postgresql stop
	/etc/init.d/redis-server stop
}

action=${1:-help}
shift 1
$action "$@"
