#!/bin/sh /etc/rc.common

START=90
STOP=10

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	local DIR=`uci -q get redis.config.DIR`
	local options=""
	if [ "${DIR}" != "" ]; then
		options="--dir ${DIR}"
	fi
	service_start /usr/bin/redis-server ${options}
}

stop() {
	service_stop /usr/bin/redis-server
}
